services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    environment:
      - ORACLE_SID=FREE
      - ORACLE_PWD=mysecretpassword  
      - ORACLE_CHARACTERSET=AL32UTF8 
    ports:
      - "1521:1521" # Default Listener Port
      - "5500:5500" # Enterprise Manager Database Express
    volumes:
      - oracle-data:/opt/oracle/data
      - ./setup:/opt/oracle/scripts/startup # Setup Scripts
    restart: always

volumes: 
  oracle-data:
